APP_OBJS += \
  $(BUILD_DIR)/apps/external/app/mini_maths/src/main.o \
  $(BUILD_DIR)/apps/external/app/mini_maths/src/controller.o \
  $(BUILD_DIR)/apps/external/app/mini_maths/src/complex_page.o \
  $(BUILD_DIR)/apps/external/app/mini_maths/src/derivation_page.o \
  $(BUILD_DIR)/apps/external/app/mini_maths/src/maths_lib.o
